In [ ]:
import pandas as pd
import numpy as np

In [ ]:
med_list_price = [55,10,20,44,78,90]

arr_med_list_price = np.array(med_list_price)

print("Numpy array",arr_med_list_price)

series_list_price = pd.Series(med_list_price)
series_array_price = pd.Series(arr_med_list_price)
print("Pandas series",series_list_price)
print("Pandas array",series_array_price)


Numpy array [55 10 20 44 78 90]
Pandas series 0    55
1    10
2    20
3    44
4    78
5    90
dtype: int64
Pandas array 0    55
1    10
2    20
3    44
4    78
5    90
dtype: int64


In [ ]:
med_price_labelled = pd.Series(med_list_price,index=['udliv','dolo','crocin','adzorb','electrol','folvite'])
print(med_price_labelled)

udliv       55
dolo        10
crocin      20
adzorb      44
electrol    78
folvite     90
dtype: int64


In [ ]:
med_price_updated =pd.Series(med_price_labelled)+3.0
med_price_updated

udliv       58.0
dolo        13.0
crocin      23.0
adzorb      47.0
electrol    81.0
folvite     93.0
dtype: float64

In [ ]:
student = ['Karthik','Suhas','Vinay','Balan']
dataframe= pd.DataFrame(student,columns=['Name'])
print(dataframe)

grades = ['A','B','C','D']
dataframe['Grades']=grades
print(dataframe)
dataframe

      Name
0  Karthik
1    Suhas
2    Vinay
3    Balan
      Name Grades
0  Karthik      A
1    Suhas      B
2    Vinay      C
3    Balan      D


Name Grades
0  Karthik      A
1    Suhas      B
2    Vinay      C
3    Balan      D

In [ ]:
operator = ["Jio","Airtel","BSNL","Vodafone"]
revenue =[150,25,66,78]
data_frame = pd.Series(revenue,index= operator)
#data_frame

data_frame[0]

<ipython-input-32-5b7762815a29>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_frame[0]


150

In [ ]:
data_frame["BSNL"]

data_frame[[0,2]]

<ipython-input-35-a5c7e2079abc>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_frame[[0,2]]


Jio     150
BSNL     66
dtype: int64

In [ ]:
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)

temp_data[:2]

day1    31
day2    28
dtype: int64

In [ ]:
temp_data['day3']

30

In [ ]:
temp_data[2:]

day3    30
day4    32
dtype: int64

In [ ]:
custId = ['Cust01','cust02','cust03','cust04','cust05']
location=['chennai','pune','blore','chennai','chennai']
gender = ['M','F','F','M','F']
type_purchase = ['electornic','food','sport','apparels','electronics']
quantity = [5,2,10,33,12]
bill = [3600,120,6853,35698,4565]

df_storage_data = pd.DataFrame({'custId':custId,'location':location,'gender':gender,'type_purchase':type_purchase,'quantity':quantity,'bill':bill})
df_storage_data



custId location gender type_purchase  quantity   bill
0  Cust01  chennai      M    electornic         5   3600
1  cust02     pune      F          food         2    120
2  cust03    blore      F         sport        10   6853
3  cust04  chennai      M      apparels        33  35698
4  cust05  chennai      F   electronics        12   4565

In [ ]:
df_storage_data.drop('gender',axis=1)
df_storage_data

custId location gender type_purchase  quantity   bill
0  Cust01  chennai      M    electornic         5   3600
1  cust02     pune      F          food         2    120
2  cust03    blore      F         sport        10   6853
3  cust04  chennai      M      apparels        33  35698
4  cust05  chennai      F   electronics        12   4565

In [ ]:
df_storage_data.loc[[0,2],'bill']
df_storage_data.iloc[::,::]

custId location gender type_purchase  quantity   bill
0  Cust01  chennai      M    electornic         5   3600
1  cust02     pune      F          food         2    120
2  cust03    blore      F         sport        10   6853
3  cust04  chennai      M      apparels        33  35698
4  cust05  chennai      F   electronics        12   4565

In [ ]:
df_storage_data['quantity']>10


0    False
1    False
2    False
3     True
4     True
Name: quantity, dtype: bool

In [ ]:
df_storage_data[:-1]

custId location gender type_purchase  quantity   bill
0  Cust01  chennai      M    electornic         5   3600
1  cust02     pune      F          food         2    120
2  cust03    blore      F         sport        10   6853
3  cust04  chennai      M      apparels        33  35698

In [ ]:
df_storage_data.head()


custId location gender type_purchase  quantity   bill
0  Cust01  chennai      M    electornic         5   3600
1  cust02     pune      F          food         2    120
2  cust03    blore      F         sport        10   6853
3  cust04   Jaipur      M      apparels        33  35698
4  cust05  chennai      F   electronics        12   4565

In [ ]:
df_storage_data.tail(2)

custId location gender type_purchase  quantity   bill
3  cust04   Jaipur      M      apparels        33  35698
4  cust05  chennai      F   electronics        12   4565

In [ ]:
df_storage_data.shape

(5, 6)

In [ ]:
df_storage_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   custId         5 non-null      object
 1   location       5 non-null      object
 2   gender         5 non-null      object
 3   type_purchase  5 non-null      object
 4   quantity       5 non-null      int64 
 5   bill           5 non-null      int64 
dtypes: int64(2), object(4)
memory usage: 368.0+ bytes


In [ ]:
df_storage_data['quantity']>1

0    True
1    True
2    True
3    True
4    True
Name: quantity, dtype: bool

In [ ]:
df_storage_data.loc[df_storage_data['quantity']>10,['custId','bill']]

custId   bill
3  cust04  35698
4  cust05   4565

In [ ]:
df_storage_data['rating']=[1,3,4,5,5]
df_storage_data

custId location gender type_purchase  quantity   bill  rating
0  Cust01  chennai      M    electornic         5   3600       1
1  cust02     pune      F          food         2    120       3
2  cust03    blore      F         sport        10   6853       4
3  cust04  chennai      M      apparels        33  35698       5
4  cust05  chennai      F   electronics        12   4565       5

In [ ]:
df_storage_data.describe()

quantity          bill
count   5.000000      5.000000
mean   12.400000  10167.200000
std    12.177849  14476.400267
min     2.000000    120.000000
25%     5.000000   3600.000000
50%    10.000000   4565.000000
75%    12.000000   6853.000000
max    33.000000  35698.000000

In [ ]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data[:2]

day  calories  duration_min
0  day1       450            30
1  day2       300            25

In [ ]:
calorie_data.drop('duration_min', axis=1)

day  calories
0  day1       450
1  day2       300
2  day3       345
3  day4       520
4  day5       600

In [ ]:
calorie_data.loc[calorie_data['calories']>500]

day  calories  duration_min
3  day4       520            39
4  day5       600            48

In [ ]:
calorie_data['calories']


0    450
1    300
2    345
3    520
4    600
Name: calories, dtype: int64

In [ ]:
calorie_data[::2]

day  calories  duration_min
0  day1       450            30
2  day3       345            29
4  day5       600            48

In [ ]:
calorie_data.loc[0]

day             day1
calories         450
duration_min      30
Name: 0, dtype: object

In [ ]:
calorie_data.loc[[1,2],'calories']
calorie_data.iloc[[1,2],[1]]

calories
1       300
2       345

In [ ]:
df_storage_data.drop('rating',axis=1,inplace=False)
df_storage_data

custId location gender type_purchase  quantity   bill  rating
0  Cust01  chennai      M    electornic         5   3600       1
1  cust02     pune      F          food         2    120       3
2  cust03    blore      F         sport        10   6853       4
3  cust04  chennai      M      apparels        33  35698       5
4  cust05  chennai      F   electronics        12   4565       5

In [ ]:
new_df=df_storage_data.drop(2,axis=0)
df_storage_data
new_df.reset_index(drop=True,inplace=True)
new_df

custId location gender type_purchase  quantity  bill
0  Cust01  chennai      M    electornic         5  3600
1  cust02     pune      F          food         2   120
2  cust05  chennai      F   electronics        12  4565

In [ ]:
df_storage_data

custId location gender type_purchase  quantity  bill
0  Cust01  chennai      M    electornic         5  3600
1  cust02     pune      F          food         2   120
2  cust03    blore      F         sport        10  6853
4  cust05  chennai      F   electronics        12  4565

In [ ]:
new_df.shape

(3, 6)

In [ ]:
df_storage_data

custId location gender type_purchase  quantity   bill
0  Cust01  chennai      M    electornic         5   3600
1  cust02     pune      F          food         2    120
2  cust03    blore      F         sport        10   6853
3  cust04  chennai      M      apparels        33  35698
4  cust05  chennai      F   electronics        12   4565

In [ ]:

customer_id =[100,101,102,103]
customer_name =['cust1','cust2','cust3','cust4']
category = ['medium','low','low','high']
sales = [363,300,250,123]

df_customer_data = pd.DataFrame({'customer_id':customer_id,'customer_name':customer_name,'category':category,'sales':sales})
df_customer_data

customer_id customer_name category  sales
0          100         cust1   medium    363
1          101         cust2      low    300
2          102         cust3      low    250
3          103         cust4     high    123

In [ ]:
customer_id =[101,103,102,105,106,107]
distance = [10,20,30,40,78,65]
sales = [300,123,250,666,789,528]
df_delivery_data = pd.DataFrame({'customer_id':customer_id,'distance':distance,'sales':sales})
df_delivery_data


customer_id  distance  sales
0          101        10    300
1          103        20    123
2          102        30    250
3          105        40    666
4          106        78    789
5          107        65    528

In [ ]:
df_concat_col = pd.concat([df_customer_data,df_delivery_data],axis=1)
df_concat_col

customer_id customer_name category  sales  customer_id  distance  sales
0          100         cust1   medium    363          101        10    300
1          101         cust2      low    300          103        20    123
2          102         cust3      low    250          102        30    250
3          103         cust4     high    123          105        40    666

In [ ]:
df_concat_row = pd.concat([df_customer_data,df_delivery_data],axis=0)
df_concat_row


customer_id customer_name category  sales  distance
0          100         cust1   medium    363       NaN
1          101         cust2      low    300       NaN
2          102         cust3      low    250       NaN
3          103         cust4     high    123       NaN
0          101           NaN      NaN    300      10.0
1          103           NaN      NaN    123      20.0
2          102           NaN      NaN    250      30.0
3          105           NaN      NaN    666      40.0

In [ ]:
df_merge = pd.merge(df_customer_data,df_delivery_data,on='customer_id')
df_merge

customer_id customer_name category  sales_x  distance  sales_y
0          101         cust2      low      300        10      300
1          102         cust3      low      250        30      250
2          103         cust4     high      123        20      123

In [ ]:
df_merge_outer = pd.merge(df_customer_data,df_delivery_data,how='outer',on='customer_id')
df_merge_outer

customer_id customer_name category  sales_x  distance  sales_y
0          100         cust1   medium    363.0       NaN      NaN
1          101         cust2      low    300.0      10.0    300.0
2          102         cust3      low    250.0      30.0    250.0
3          103         cust4     high    123.0      20.0    123.0
4          105           NaN      NaN      NaN      40.0    666.0
5          106           NaN      NaN      NaN      78.0    789.0
6          107           NaN      NaN      NaN      65.0    528.0

In [ ]:
df_merge_inner = pd.merge(df_customer_data,df_delivery_data,how='inner',on='customer_id')
df_merge_inner

customer_id customer_name category  sales_x  distance  sales_y
0          101         cust2      low      300        10      300
1          102         cust3      low      250        30      250
2          103         cust4     high      123        20      123

In [ ]:
df_merge_right = pd.merge(df_customer_data,df_delivery_data,how='right',on='customer_id')
df_merge_right

customer_id customer_name category  sales_x  distance  sales_y
0          101         cust2      low    300.0        10      300
1          103         cust4     high    123.0        20      123
2          102         cust3      low    250.0        30      250
3          105           NaN      NaN      NaN        40      666
4          106           NaN      NaN      NaN        78      789
5          107           NaN      NaN      NaN        65      528

In [ ]:
df_merge_left = pd.merge(df_customer_data,df_delivery_data,how='left',on='customer_id')
df_merge_left

customer_id customer_name category  sales_x  distance  sales_y
0          100         cust1   medium      363       NaN      NaN
1          101         cust2      low      300      10.0    300.0
2          102         cust3      low      250      30.0    250.0
3          103         cust4     high      123      20.0    123.0

In [ ]:
df_join = df_customer_data.join(df_delivery_data,how='inner',lsuffix='_left',rsuffix='_right')
df_join

customer_id_left customer_name category  sales_left  customer_id_right  \
0               100         cust1   medium         363                101   
1               101         cust2      low         300                103   
2               102         cust3      low         250                102   
3               103         cust4     high         123                105   

   distance  sales_right  
0        10          300  
1        20          123  
2        30          250  
3        40          666

In [ ]:
df_storage_data['gender'].value_counts()

gender
F    3
M    1
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Create a sample Series
my_series = pd.Series([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Get the value counts (absolute counts)
counts = my_series.value_counts()
print(counts)

# Get the normalized value counts (relative frequencies)
normalized_counts = my_series.value_counts(normalize=True)
print(normalized_counts)


4    4
3    3
2    2
1    1
Name: count, dtype: int64
4    0.4
3    0.3
2    0.2
1    0.1
Name: proportion, dtype: float64


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd "/content/drive/MyDrive/PGP_AI_ML_GREAT_LEARNING/WEEK 01_AND_02/WEEK_02"

/content/drive/MyDrive/PGP_AI_ML_GREAT_LEARNING/WEEK 01_AND_02/WEEK_02


In [ ]:
!ls

books.csv			  Hands_on_Notebook_Pandas-1.ipynb  StockData.xlsx
Hands_on_Notebook_NumPy_v1.ipynb  StockData.csv


In [ ]:
df_books = pd.read_csv('books.csv')
df_books

title  \
0                           The Hunchback of Notre-Dame   
1     La Cucina Di Lidia: Recipes and Memories from ...   
2                                     Breach of Promise   
3                     Brief Interviews with Hideous Men   
4     The Killing Dance (Anita Blake  Vampire Hunter...   
...                                                 ...   
4995                                 The Complete Works   
4996                               Shipwreck (Island I)   
4997           Every Night Italian: Every Night Italian   
4998                                     Go Down  Moses   
4999  The Avignon Quintet: Monsieur  Livia  Constanc...   

                           author  average_rating         isbn13  \
0                     Victor Hugo            4.00  9780345472427   
1     Lidia Matticchio Bastianich            4.14  9780767914222   
2                James Scott Bell            4.00  9780310243878   
3            David Foster Wallace            3.86  9780349111889   
4             Laurell K. Hamilton            4.13  9780425209066   
...                           ...             ...            ...   
4995          Michel de Montaigne            4.44  9781400040216   
4996                Gordon Korman            3.80  9780439023313   
4997               Giuliano Hazan            3.79  9780684800288   
4998             William Faulkner            3.93  9780679732174   
4999             Lawrence Durrell            4.07  9780571225552   

     language_code  num_pages  ratings_count  text_reviews_count  \
0            en-US      534.0            140                  22   
1            en-GB      288.0             48                   3   
2              eng      345.0            368                  36   
3              eng      273.0          18335                1155   
4            en-US      368.0          59524                 946   
...            ...        ...            ...                 ...   
4995           eng     1392.0            166                  13   
4996           eng        NaN            103                  14   
4997           eng      256.0             70                   2   
4998           eng      365.0           8289                 370   
4999         en-US     1376.0            287                  23   

                   publisher  year  
0             Modern Library  2004  
1            Clarkson Potter  2003  
2                  Zondervan  2004  
3                     Abacus  2000  
4          Berkley Hardcover  2006  
...                      ...   ...  
4995      Everyman's Library  2003  
4996  Scholastic Audio Books  2007  
4997                Scribner  2000  
4998                 Vintage  1991  
4999           Faber & Faber  2004  

[5000 rows x 10 columns]

In [ ]:
df_books.shape

(5000, 10)

In [ ]:
df_books.describe()

average_rating        isbn13    num_pages  ratings_count  \
count     5000.000000  5.000000e+03  4967.000000   5.000000e+03   
mean         3.931932  9.752758e+12   341.094021   2.017549e+04   
std          0.348741  5.129254e+11   230.986115   1.175026e+05   
min          0.000000  8.987060e+09     1.000000   0.000000e+00   
25%          3.770000  9.780345e+12   200.000000   1.050000e+02   
50%          3.960000  9.780571e+12   304.000000   7.915000e+02   
75%          4.140000  9.780871e+12   416.500000   5.348750e+03   
max          5.000000  9.789879e+12  3342.000000   2.457092e+06   

       text_reviews_count         year  
count         5000.000000  5000.000000  
mean           592.688600  2000.131800  
std           2539.539004     8.069043  
min              0.000000  1913.000000  
25%              9.000000  1998.000000  
50%             49.000000  2003.000000  
75%            249.000000  2005.000000  
max          55843.000000  2019.000000

In [ ]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               5000 non-null   object 
 1   author              5000 non-null   object 
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64  
 4   language_code       4923 non-null   object 
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64  
 7   text_reviews_count  5000 non-null   int64  
 8   publisher           5000 non-null   object 
 9   year                5000 non-null   int64  
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB


In [ ]:
df_books[(df_books['language_code']=='spa') & (df_books['year']>2000)]

title  \
21                      Los funerales de la Mamá Grande   
53    La Emperatriz tras el velo (Trilogía Taj Mahal...   
69                             La casa de los espíritus   
93                                  Ya Sé Que Te Quiero   
107                                 Secretos De Familia   
...                                                 ...   
4804                                      Muerte Blanca   
4832  Entrevista con el vampiro (Crónicas vampíricas...   
4890         Isabel: Princesa De Castilla  España  1466   
4907                                     Ve  perro ¡Ve!   
4951                                El librero de Kabul   

                      author  average_rating         isbn13 language_code  \
21    Gabriel García Márquez            3.78  9780307350329           spa   
53           Indu Sundaresan            4.04  9788425337604           spa   
69            Isabel Allende            4.23  9780060951306           spa   
93             Billy Crystal            4.19  9780060845988           spa   
107              Julia Glass            3.57  9788496525030           spa   
...                      ...             ...            ...           ...   
4804           Clive Cussler            3.91  9780307343260           spa   
4832               Anne Rice            3.99  9788466616201           spa   
4890           Carolyn Meyer            3.71  9788478886746           spa   
4907            P.D. Eastman            4.09  9780375823619           spa   
4951          Åsne Seierstad            3.76  9789706519245           spa   

      num_pages  ratings_count  text_reviews_count                publisher  \
21        160.0           4694                 133            Plaza y Janes   
53        382.0              2                   1    Grijalbo Mondadori Sa   
69        454.0            608                  38    HarperCollins Espanol   
93         40.0              0                   0                     Rayo   
107       528.0              0                   1              Puzzle-Roca   
...         ...            ...                 ...                      ...   
4804      421.0              2                   0               Debolsillo   
4832      463.0           1307                  93              Ediciones B   
4890      184.0              8                   0               Salamandra   
4907       24.0             33                   2  Random House Para Ninos   
4951      285.0            112                  18             Grupo Océano   

      year  
21    2006  
53    2003  
69    2001  
93    2006  
107   2006  
...    ...  
4804  2005  
4832  2005  
4890  2001  
4907  2003  
4951  2004  

[84 rows x 10 columns]

In [ ]:
df_books[(df_books['num_pages']>500) & (df_books['year']>2010)]

title               author  \
2045  Billy Budd  Sailor and Other Uncompleted Writi...      Herman Melville   
2775          Rick Steves' Europe Through the Back Door          Rick Steves   
3075                                          The Iliad                Homer   
3157                    George Washington's Sacred Fire    Peter A. Lillback   
3546                                  The Will to Power  Friedrich Nietzsche   

      average_rating         isbn13 language_code  num_pages  ratings_count  \
2045            3.11  9780810111141           eng     1016.0              0   
2775            4.24  9781566918084           eng      808.0           3569   
3075            3.86  9781904633389           eng      542.0             64   
3157            4.18  9780978605261           eng     1200.0            694   
3546            4.05  9780394704371           eng      575.0           7931   

      text_reviews_count                publisher  year  
2045                   0  Northwestern Univ Press  2017  
2775                  70            Avalon Travel  2017  
3075                   8      Collector's Library  2011  
3157                  63   Providence Forum Press  2011  
3546                 132            Vintage Books  2011

In [ ]:
df_books[df_books['author']=='Agatha Christie'].shape

(21, 10)

In [ ]:
df_books.loc[[1,4],['language_code', 'num_pages', 'ratings_count']]

language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [ ]:
df_books[(df_books['publisher']=='DAW') & (df_books['average_rating']>4.0)]

title           author  \
71                           By the Sword (Valdemar)  Mercedes Lackey   
871         Storm Rising (Valdemar: Mage Storms  #2)  Mercedes Lackey   
1523       Phoenix and Ashes (Elemental Masters  #3)  Mercedes Lackey   
1583  To Battle the Gods (Jalav  Amazon Warrior  #5)     Sharon Green   
3726        Oathblood (Valdemar: Vows and Honor  #3)  Mercedes Lackey   
4367                     Joust (Dragon Jousters  #1)  Mercedes Lackey   

      average_rating         isbn13 language_code  num_pages  ratings_count  \
71              4.25  9780886774639           eng      492.0          18531   
871             4.02  9780886777128         en-US      412.0          10781   
1523            4.01  9780756402723           eng      480.0           6980   
1583            4.07  9780886771287           eng      446.0             87   
3726            4.06  9780886777739         en-GB      394.0           9786   
4367            4.02  9780756401535           eng      448.0          10113   

      text_reviews_count publisher  year  
71                   249       DAW  1991  
871                   86       DAW  1996  
1523                 229       DAW  2005  
1583                   1       DAW  1986  
3726                 103       DAW  1998  
4367                 263       DAW  2004

In [ ]:
df_books['num_pages'].median()

304.0

In [ ]:
df_books['num_pages'].describe()

count    4967.000000
mean      341.094021
std       230.986115
min         1.000000
25%       200.000000
50%       304.000000
75%       416.500000
max      3342.000000
Name: num_pages, dtype: float64

In [ ]:
df_books['num_pages'].mean()

341.0940205355345

In [ ]:
df_books[df_books['year']==2010]

title  \
40    The Walking Dead  Book One (The Walking Dead #...   
359        Things: A Story of the Sixties; A Man Asleep   
425   The Gap Into Vision: Forbidden Knowledge (Gap ...   
985                                     Never Let Me Go   
1696           The Unexpected Guest: A Play In Two Acts   
1789  A Short History of Nearly Everything (Illustra...   
2620                                         The Client   
2695                                      Lord of Light   
2706         Pimsleur German Level 1 CD: [Lessons 1-30]   
3079                             Tim Burton: Interviews   
3724                                     Less Than Zero   
4460                                     Riddley Walker   
4650  The Beatles' Story on Capitol Records  Part Tw...   
4891   Judy Moody Declares Independence (Judy Moody #6)   
4914  Earthquake in the Early Morning (Magic Tree Ho...   

                          author  average_rating         isbn13 language_code  \
40                Robert Kirkman            4.35  9781582406190           eng   
359                Georges Perec            3.98  9781567921571           eng   
425         Stephen R. Donaldson            3.99  9780553297607         en-US   
985               Kazuo Ishiguro            3.82  9781400078776           eng   
1696             Agatha Christie            3.83  9780573014673           eng   
1789                 Bill Bryson            4.21  9780385663557           eng   
2620                John Grisham            4.00  9780385339087           eng   
2695               Roger Zelazny            4.10  9780060567231           eng   
2706  Pimsleur Language Programs            4.23  9780743518369           eng   
3079              Kristian Fraga            4.26  9781578067596           eng   
3724           Bret Easton Ellis            3.58  9780679781493           eng   
4460               Russell Hoban            4.03  9780747559047           eng   
4650                Bruce Spizer            4.72  9780966264920           eng   
4891              Megan McDonald            4.08  9780763628000           eng   
4914           Mary Pope Osborne            3.94  9780679890706           eng   

      num_pages  ratings_count  text_reviews_count  \
40        304.0          34751                1346   
359       221.0           1062                  63   
425       480.0           5020                 101   
985       288.0         380646               22957   
1696      100.0           2813                 167   
1789      624.0             28                   7   
2620      483.0         367399                1978   
2695      296.0          23392                1104   
2706       16.0             58                  10   
3079      192.0            103                   7   
3724      208.0          55900                2543   
4460      236.0            305                  44   
4650      264.0             29                   0   
4891      160.0           3884                 132   
4914       96.0           6816                 227   

                            publisher  year  
40                       Image Comics  2010  
359         David R. Godine Publisher  2010  
425                            Bantam  2010  
985                     Vintage Books  2010  
1696                Samuel French Ltd  2010  
1789                    Anchor Canada  2010  
2620                            Delta  2010  
2695                   Harper Voyager  2010  
2706                         Pimsleur  2010  
3079  University Press of Mississippi  2010  
3724                    Vintage Books  2010  
4460                       Bloomsbury  2010  
4650    Four Ninety-Eight Productions  2010  
4891                       Candlewick  2010  
4914   Random House for Young Readers  2010

In [ ]:
df_books['']

In [ ]:
df_books.loc[df_books['average_rating']>4]

title  \
1     La Cucina Di Lidia: Recipes and Memories from ...   
4     The Killing Dance (Anita Blake  Vampire Hunter...   
5          The Hand of Chaos (The Death Gate Cycle  #5)   
6                                       On Intelligence   
11                        Merlin's Tour of the Universe   
...                                                 ...   
4991                                       'Salem's Lot   
4992                  A Mad People's History of Madness   
4993     A Christmas Carol (Great Illustrated Classics)   
4995                                 The Complete Works   
4999  The Avignon Quintet: Monsieur  Livia  Constanc...   

                           author  average_rating         isbn13  \
1     Lidia Matticchio Bastianich            4.14  9780767914222   
4             Laurell K. Hamilton            4.13  9780425209066   
5                   Margaret Weis            4.06  9780553563696   
6                    Jeff Hawkins            4.12  9780805078534   
11            Neil deGrasse Tyson            4.02  9780385488358   
...                           ...             ...            ...   
4991                 Stephen King            4.02  9780965772419   
4992                Dale Peterson            4.33  9780822953319   
4993             Malvina G. Vogel            4.36  9781596792371   
4995          Michel de Montaigne            4.44  9781400040216   
4999             Lawrence Durrell            4.07  9780571225552   

     language_code  num_pages  ratings_count  text_reviews_count  \
1            en-GB      288.0             48                   3   
4            en-US      368.0          59524                 946   
5              eng      446.0          16301                 117   
6              eng      261.0           5347                 396   
11             eng      318.0            305                  27   
...            ...        ...            ...                 ...   
4991           eng      405.0           1039                 130   
4992           eng      384.0              9                   0   
4993           eng      238.0            466                  31   
4995           eng     1392.0            166                  13   
4999         en-US     1376.0            287                  23   

                           publisher  year  
1                    Clarkson Potter  2003  
4                  Berkley Hardcover  2006  
5                            Spectra  1993  
6               St. Martin's Griffin  2005  
11                 Main Street Books  1997  
...                              ...   ...  
4991                       Doubleday  1975  
4992  University of Pittsburgh Press  1982  
4993         Abdo Publishing Company  2005  
4995              Everyman's Library  2003  
4999                   Faber & Faber  2004  

[2115 rows x 10 columns]

In [ ]:
df_books['average_rating'].mean()

3.9319319999999998

AttributeError: 'DataFrame' object has no attribute 'header'

In [ ]:
df_books.iloc[0:5,0:4]

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13  
0                  Victor Hugo            4.00  9780345472427  
1  Lidia Matticchio Bastianich            4.14  9780767914222  
2             James Scott Bell            4.00  9780310243878  
3         David Foster Wallace            3.86  9780349111889  
4          Laurell K. Hamilton            4.13  9780425209066

In [ ]:
df_books.head()

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13 language_code  \
0                  Victor Hugo            4.00  9780345472427         en-US   
1  Lidia Matticchio Bastianich            4.14  9780767914222         en-GB   
2             James Scott Bell            4.00  9780310243878           eng   
3         David Foster Wallace            3.86  9780349111889           eng   
4          Laurell K. Hamilton            4.13  9780425209066         en-US   

   num_pages  ratings_count  text_reviews_count          publisher  year  
0      534.0            140                  22     Modern Library  2004  
1      288.0             48                   3    Clarkson Potter  2003  
2      345.0            368                  36          Zondervan  2004  
3      273.0          18335                1155             Abacus  2000  
4      368.0          59524                 946  Berkley Hardcover  2006

In [ ]:
list_ = [9,8,7,6,5,4,3,2,1]
np_arr = np.array(list_)
print(np_arr)

np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

[9 8 7 6 5 4 3 2 1]


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
np.arange(start=1, stop=10, step=1).reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array_1 = np.linspace(0,20,6)
print(array_1)
array_2 = np.arange(0,20,6)
print(array_2)


[ 0.  4.  8. 12. 16. 20.]
[ 0  6 12 18]


In [ ]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])

np.mean(mat)

131.66666666666666

In [ ]:
a = np.arange(0,20)
print(a<0)



[False False False False False False False False False False False False
 False False False False False False False False]


In [ ]:
np.cos([0, 1, 2, 3, 4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
new_list

[1, 2, 3, 4, 5, 6]

In [ ]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
new_array

array([5, 7, 9])

In [ ]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1]=5
mat

array([[1, 2, 1],
       [5, 5, 5],
       [1, 8, 9]])

In [ ]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
print(new_array)
final_array = new_array*array_1
print(final_array[2])

[1 5 7 7 9]
21


In [ ]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])

n3= np.dot(n1,n2)
n3

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [ ]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [ ]:
demo_matrix[0:3, 1:3]


array([[35, 74],
       [37, 37],
       [39, 93]])

In [ ]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [2]:
import pandas as pd
bucket = [3.14,'pi',2.718]
series = pd.Series(bucket)

df= pd.read_csv()

In [4]:
items = {'col':[1,2,3],'col2':[3,4,5]}
df_from_dict = pd.DataFrame(items)
df_from_dict

col  col2
0    1     3
1    2     4
2    3     5

In [7]:
import numpy as np
list_sales = [200,450,150,400,500,700]
sales_array=np.array(list_sales)
print(sales_array)
min_index=np.argmin(sales_array)
max_index=np.argmax(sales_array)
print(min_index)
print(max_index)

[200 450 150 400 500 700]
2
5


In [8]:
import numpy as np
sales_data=np.array([100,150,200,250,300])
sales_data

array([100, 150, 200, 250, 300])