In [1]:
import numpy as np

In [5]:
list_test = [[1,2,3,4],[7,8,9,10]]
print("List: ",list_test)
print("List type: ", type(list_test))


np_array = np.array(list_test)
print("Numpy array: ",np_array)
print("Numpy array type: ", type(np_array))


List:  [[1, 2, 3, 4], [7, 8, 9, 10]]
List type:  <class 'list'>
Numpy array:  [[ 1  2  3  4]
 [ 7  8  9 10]]
Numpy array type:  <class 'numpy.ndarray'>


In [15]:
a_Range = np.arange(0,100,10)
print(a_Range)

[ 0 10 20 30 40 50 60 70 80 90]


In [14]:
a_linespace = np.linspace(0,10,10)
print(a_linespace)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [28]:
matrix_zero = np.zeros([2,3])
print(matrix_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
matrix_one= np.ones([10,3])
print(matrix_one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
matrix_eye = np.eye(5)
print(matrix_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
vect= np.arange(10,20,3)
print(vect)

[10 13 16 19]


In [27]:
vect= np.linspace(10,20,3)
print(vect)

[10. 15. 20.]


In [44]:
re_shp_array=np.arange(0,12)
print(re_shp_array)

re_shp_array=re_shp_array.reshape(4,3)
print(re_shp_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
print("Sin Function: ",np.sin(vect))
print("cos Function: ",np.cos(vect))
print("tan Function: ",np.tan(vect))

print("Expo:", np.exp(2))
print("Log:", np.log(2))


Sin Function:  [-0.54402111  0.65028784  0.91294525]
cos Function:  [-0.83907153 -0.75968791  0.40808206]
tan Function:  [ 0.64836083 -0.8559934   2.23716094]
Expo: 7.38905609893065
Log: 0.6931471805599453


In [45]:
lst_1 =[1,2,3]
lst_2 =[4,5,6]

print(lst_1+lst_2)

[1, 2, 3, 4, 5, 6]


In [53]:
np_arr_01 = np.array(lst_1)
np_arr_02 = np.array(lst_2)

print(np_arr_01+np_arr_02)
print(np_arr_01-np_arr_02)
print(np_arr_01/np_arr_02)
print(np_arr_01%np_arr_02)
print(np_arr_01[::-1])

print("Inverse: ",1/np_arr_01)
print("Powers: ",np_arr_01**2)
print("Log: ",np.log(np_arr_01))
print("Exp: ",np.exp(np_arr_01))

print( "POERS: ",np_arr_01**np_arr_02)


[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 2 3]
[3 2 1]
Inverse:  [1.         0.5        0.33333333]
Powers:  [1 4 9]
Log:  [0.         0.69314718 1.09861229]
Exp:  [ 2.71828183  7.3890561  20.08553692]
POERS:  [  1  32 729]


In [57]:
np_Mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_Mat)
np_eye_mat = np.eye(3)
print(np_eye_mat)

print("Addition: ",np_Mat+np_eye_mat)
print("SUB:",np_Mat-np_eye_mat)
print("DIV:",np_Mat/np_eye_mat)
print("MUL:", np_Mat*np_eye_mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Addition:  [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
SUB: [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
DIV: [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
MUL: [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


<ipython-input-57-4e8486b215f9>:8: RuntimeWarning: divide by zero encountered in divide
  print("DIV:",np_Mat/np_eye_mat)


In [63]:
mat_01 = np.arange(1,10).reshape(3,3)
mat_02 = np.arange(11,20).reshape(3,3)
mat_03= np.ones([3,3])
mat_04= np.ones([3,3])

print(mat_01)
print(mat_02)

print("ONE:",mat_04  @ mat_03)
print("ONE:",mat_04  * mat_03)


print(mat_01 @ mat_02)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
ONE: [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
ONE: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [64]:
np.transpose(mat_01)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [65]:
vec1 = [10,15,20]
vec2 = [15,25,35]
print(vec1+vec2)

[10, 15, 20, 15, 25, 35]


In [70]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1 )
print(vec2)
print(vec1+vec2)
print(vec1-vec2)
print(vec1*vec2)
print(vec1/vec2)

[20. 30. 40. 50.]
[100. 110. 120.]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [73]:
vec = np.arange(2,5,1)
print(vec)
print(1/vec)
print(vec**2)

[2 3 4]
[0.5        0.33333333 0.25      ]
[ 4  9 16]


In [74]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]


<ipython-input-74-0e6adcba2ca7>:3: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)


In [77]:
mat_02
print(mat_02)
print("Min: ", np.min(mat_02))
print("Max: ", np.max(mat_02))

[[11 12 13]
 [14 15 16]
 [17 18 19]]
Min:  11
Max:  19


In [79]:
rand_mat_01 = np.random.randn(5,5)
print(rand_mat_01)

[[ 0.63205005  0.30727848  0.10282591 -1.0042122   0.46872966]
 [ 0.74047109 -0.26744509 -0.43345209 -0.63264826 -0.7552645 ]
 [ 0.96682492 -1.24528907  0.32083687  0.06032845  0.05270346]
 [-0.98618114  0.71540588  0.43709403 -0.4987307  -0.65540899]
 [-0.97374173 -1.56081063 -1.08719485  0.0427874  -0.22879703]]


In [83]:
rand_mat_02 = np.random.randn(6)
print(rand_mat_02)
print(rand_mat_02.reshape(2,3))

[ 1.01704866 -0.27254818 -0.48240031 -0.02300735 -0.52751778 -0.79727208]
[[ 1.01704866 -0.27254818 -0.48240031]
 [-0.02300735 -0.52751778 -0.79727208]]


In [87]:
rand_mat_03= np.random.randn(5,5)
print(rand_mat_03)
print("MAen: ",np.mean(rand_mat_03))
print("Var: ",np.var(rand_mat_03))
print("Std: ",np.std(rand_mat_03))

[[-0.90103488  0.09059685 -1.90039313 -0.11593143 -0.85783076]
 [ 1.6347782   1.31914071  0.17433031  0.62359496 -0.19194554]
 [-1.85822878 -1.16683008 -1.09706036  0.33040893 -2.57559144]
 [ 0.16243332 -1.32792941  1.0495408  -0.52768892  1.25696423]
 [ 0.08506596  0.87864653 -0.99902196 -0.78624111 -1.56798467]]
MAen:  -0.33072846680689066
Var:  1.1871902458776091
Std:  1.0895826016771786


In [94]:
ran_int = np.random.randint(1,50,[10,10])
print(ran_int)

[[11 44 37 28 38 15 40 46 23 47]
 [41  4 30 21 16 27  5 19 24 11]
 [18 23  7 12 20  4 35 35 49 42]
 [ 3 36  7  9 41 47  8  7 40 42]
 [38 25 24 10 38 34  7 14 19 37]
 [10 17 37 11  3 21 47 12  3 10]
 [33 42  9 26 25 30 26 32 43 26]
 [ 5 49 25 44 48 27 49 40 38 15]
 [10 43 20  5  5 40 40 37 29 37]
 [41  5 10 42 29  7 10 17 11 30]]


In [96]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(mat1)
print(np.min(mat1))
print(np.max(mat1))

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
-9
-1


In [122]:
acc_arr= np.arange(30).reshape([3,10])
acc_arr_01= np.arange(30)
print(acc_arr)

print(acc_arr[::-1])

print(acc_arr[2][9])

acc_arr_01[2:-1]= 0
print(acc_arr_01)

acc_arr_01[acc_arr_01==0]= 100
print(acc_arr_01)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]
29
[ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0 29]
[100   1 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100  29]


In [123]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [124]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [125]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [145]:
sub_mat = np.arange(0,20).reshape(4,5)
print(sub_mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [139]:
sub_mat[1:2,2:5] = 10000
print(sub_mat)

[[    0     1     2     3     4]
 [    5     6 10000 10000 10000]
 [   10    11    12    13    14]
 [   15    16    17    18    19]]


In [146]:
sub_mat_01= sub_mat[1:2,2:5]
print(sub_mat_01)
sub_mat_01[:]=-1
print(sub_mat_01)

[[7 8 9]]
[[-1 -1 -1]]


In [160]:
matrix = np.arange(1,17).reshape(4,4)
#matrix[0:2,1:2] = 0
print(matrix)

print(matrix[1:3,2:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 7  8]
 [11 12]]


In [150]:
#import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
array2 = array1
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
